add datastream-for-bigquery
wedinc/wedinc.github.io pull request #29
Opened 2023-11-18 12:00 UTC by thimi0412

Datastremの記事を追加

2023-11-18 12:00 UTC, thimi0412 commented
画像の場所だけよくわかんなかったっす。

2023-11-20 04:50 UTC, yanskun requested changes

2023-11-20 04:50 UTC, yanskun commented on content/datastream-for-bigquery.md
> +# 導入の経緯
諸説あるけど H1 が複数あるの良くない気がする

2023-11-20 04:50 UTC, yanskun commented on content/datastream-for-bigquery.md
> +published: false
YAML Frontmatter は、https://github.com/wedinc/wedinc.github.io/blob/main/content/.template.md を参照してほしい

2023-11-20 05:09 UTC, ryuya-matsunawa requested changes

2023-11-20 05:09 UTC, ryuya-matsunawa commented on content/datastream-for-bigquery.md
> +しかし`shimiz`→を`shimizu2`に更新して`updated_at`も更新されるとidが重複してまう。
```suggestion
しかし`shimizu`→を`shimizu2`に更新して`updated_at`も更新されるとidが重複してまう。
```

2023-11-20 11:32 UTC, thimi0412 commented on content/datastream-for-bigquery.md
> +published: false
[5c23405](https://github.com/wedinc/wedinc.github.io/pull/29/commits/5c2340543b9c72fc491f15aa88c31f52662ab925)

2023-11-20 11:33 UTC, thimi0412 commented on content/datastream-for-bigquery.md
> +# 導入の経緯
[a5e47d7](https://github.com/wedinc/wedinc.github.io/pull/29/commits/a5e47d728e4d88544626c96baf68d32437a712e2)

2023-11-21 10:08 UTC, yanskun approved these changes
![LGTM](https://68.media.tumblr.com/130a3e57e2745c0cfb757e6ecae5f4ac/tumblr_oabbmdOo0L1u1fcuyo5_400.gif)

2023-11-24 02:54 UTC, ryuya-matsunawa approved these changes
LGTM!

2023-11-27 02:16 UTC, merged