Cn blog 01
wedinc/wedinc.github.io pull request #30
Opened 2023-11-22 04:17 UTC by catabon55

2023-11-24 07:04 UTC, yanskun requested changes

2023-11-24 07:04 UTC, yanskun commented on content/20231121-executor-meets-gcsfuse.md
> +普段はNotebook上で小さめのデータで対話的にあれこれ試して、いけそうとなったら大規模なデータに対して[Executor](https://cloud.google.com/vertex-ai/docs/workbench/managed/executor?hl=ja)を使ってNotebookを別プロセスで実行しています。
Markdown 上で改行するには

```suggestion
仕事では主にVertex AIのWorkbenchを用いて作業をしています。JupyterLab Notebookで作業できて割と快適です。  
普段はNotebook上で小さめのデータで対話的にあれこれ試して、いけそうとなったら大規模なデータに対して[Executor](https://cloud.google.com/vertex-ai/docs/workbench/managed/executor?hl=ja)を使ってNotebookを別プロセスで実行しています。
```
半角スペース2つ必要なのです
ref; https://daringfireball.net/projects/markdown/syntax

2023-11-27 01:00 UTC, catabon55 commented on content/20231121-executor-meets-gcsfuse.md
> +普段はNotebook上で小さめのデータで対話的にあれこれ試して、いけそうとなったら大規模なデータに対して[Executor](https://cloud.google.com/vertex-ai/docs/workbench/managed/executor?hl=ja)を使ってNotebookを別プロセスで実行しています。
ご指摘ありがとう！反映しました。

2023-11-27 04:49 UTC, yanskun requested changes

2023-11-27 04:49 UTC, yanskun commented on content/20231121-executor-meets-gcsfuse.md
> +BigQuery上のテーブルにNotebookでアクセスするとき、ふだんは何も指定せず
ごめんなさい、全部見れてないですが、
改行したいけど、改行されてないパターンの箇所とか他にもあるかもしれないので、ローカルで確認しちゃうのが楽ちんだと思います。

```suggestion
[公式ドキュメント](https://cloud.google.com/vertex-ai/docs/workbench/managed/executor?hl=ja#explicit-project-selection)にも書いてありますが、  
BigQuery上のテーブルにNotebookでアクセスするとき、ふだんは何も指定せず
```

2023-11-27 04:59 UTC, catabon55 commented on content/20231121-executor-meets-gcsfuse.md
> +BigQuery上のテーブルにNotebookでアクセスするとき、ふだんは何も指定せず
了解です。ソースで改行していても、表示では改行しなくてもよいところもあるので、一通り確認して適宜修正しました。

2023-11-27 05:05 UTC, yanskun approved these changes
![LGTM](http://livedoor.blogimg.jp/dqnplus/imgs/1/0/104820ed.jpg)

2023-11-27 05:16 UTC, wed-hideto-obara approved these changes
終わりに、が味わい深かったです。

2023-11-27 08:13 UTC, merged