content: add created the blog
wedinc/wedinc.github.io pull request #33
Opened 2023-11-24 06:15 UTC by yanskun

2023-11-27 03:27 UTC, TonoFumi commented on content/created-the-blog.md
> +- Deploy
Hostingの方が適切では？

2023-11-27 03:28 UTC, TonoFumi commented on content/created-the-blog.md
> +{organization}.github.io というリポジトリ名にしないといけないっぽかったので、そうしました。
社外の人も見ることを考えると、もう少し良い書き方がありそう

分かってないこと自体は問題ないんですが、こういう書き方をブログでされると、自分だったらエンジニアのレベル低いかも？って疑う
`GitHub Pages のことあんまりよくわかってないんですが、`

2023-11-27 03:34 UTC, TonoFumi commented on content/created-the-blog.md
> +正直、公式のドキュメントに従って、ぽちぽちやってただけなので覚えてません。
こういう表現のほうが適切かな？
`公式のドキュメント通りにやればできるのでとても簡単です`

2023-11-27 03:34 UTC, TonoFumi commented on content/created-the-blog.md
> +Engineer がより Engineer らしく自己表現できる遊び場になれば嬉しいです。
とても良い締め

2023-11-27 09:35 UTC, dahhara requested changes

2023-11-27 09:35 UTC, dahhara commented on content/created-the-blog.md
> +GitHub が大好きなので、 [wedinc](https://github.com/wedinc) でも GitHub Pages を使って、何か作れないかなと思っていました。
(suggest)
下記のように整理すると流れがきれいかなと思いましたが、どうです？
細かいニュアンスはさておき、なぜ技術ブログが書けない状況で煽られたかの説明は欲しいと思いました！

## Issue
WED のエンジニアは技術に対して並々ならぬ情熱があるにも関わらず、発信する場所を組織として運用できていない状態がありました。

## Will
また、私は GitHub が大好きなので、 [wedinc](https://github.com/wedinc) でも GitHub Pages を使って、何か作れないかなと思っていました。  

## Fact
そんなときにとあるメンバーから  
**「安田さん、いつになったら技術ブログ書けるようになるんですか？」**  
**「技術ブログ、整備するって言ってましたよね？」**
**「他サービスでいつでも投稿できるように下書きだけしているんですけどね？」**  
とめちゃくちゃ、めちゃくちゃに煽られました。

## Result
Nuxt3 + GitHub Pages でなら、サクッと作る自信があったので、作ってみました。

2023-11-27 09:35 UTC, dahhara commented on content/created-the-blog.md
> +
空行要らないかも？
```suggestion
```

2023-11-27 09:35 UTC, dahhara commented on content/created-the-blog.md
> +Engineer Team の MTG で良く言われます。
```suggestion
このブログを立ち上げた後、Engineer Team の MTG で良く言われます。  
```

2023-11-27 13:07 UTC, TonoFumi approved these changes

2023-11-28 01:41 UTC, yanskun commented on content/created-the-blog.md
> +GitHub が大好きなので、 [wedinc](https://github.com/wedinc) でも GitHub Pages を使って、何か作れないかなと思っていました。
yosaso

2023-11-28 03:31 UTC, dahhara approved these changes
![LGTM](https://image.lgtmoon.dev/229316)

2023-11-28 03:32 UTC, merged