Add article about Ruby WASM
wedinc/wedinc.github.io pull request #44
Opened 2023-11-28 10:38 UTC by ym19851201

SSIA

2023-11-28 10:38 UTC, ym19851201 commented on content/20231128-ruby-wasm.md
> +}
コード載せていい？

2023-11-28 10:38 UTC, ym19851201 commented on content/20231128-ruby-wasm.md
> +![victor.png](<content/20231128-ruby-wasm/victor.png>)
Victorの画像貼っていい？

2023-11-28 10:45 UTC, knu approved these changes
おもしろい内容になっていると思います！
実用レポートとしても貴重そう👍✨

2023-11-28 11:31 UTC, dahhara requested changes
全体的にユーモラスな文章でありつつ、課題解決が面白い記事だと思いました！
画像の解像度だけ気になったので、確認をお願いしますー

2023-11-28 11:31 UTC, dahhara commented on content/20231128-ruby-wasm.md
> +}
ONE 及び Victor の仕様に依存するコードじゃなさそうなので、良いと思いました:lgtm:

2023-11-28 11:31 UTC, dahhara commented on content/20231128-ruby-wasm.md
> +![victor.png](<content/20231128-ruby-wasm/victor.png>)
(suggest)
こちらも良いのですが、ブラウザで見たら解像度が若干荒そう？だったので、リサイズするか解像度高いキャプチャにしたほうが見栄えがよさそうです
<img width="1178" alt="image" src="https://github.com/wedinc/wedinc.github.io/assets/95737849/b6fe4155-133c-4edd-b95e-50f527b17433">

2023-11-29 01:05 UTC, yanskun approved these changes
意図した通りになっていれば、問題ないです！
https://github.com/wedinc/wedinc.github.io/pull/32#discussion_r1407397929

https://github.com/wedinc/wedinc.github.io/pull/32#discussion_r1407412075

![LGTM](http://www.goodjob-okinawa.info/wp-content/themes/goodjob/images/img-main.gif)

2023-11-29 01:49 UTC, ym19851201 commented
@yanskun 改行微調整しました :kansha:

@dahhara 解像度上げました

2023-11-29 01:51 UTC, dahhara approved these changes
![LGTM](https://image.lgtmoon.dev/229423)

2023-11-29 02:58 UTC, merged