DB Migration Ganbatta KIJI
wedinc/wedinc.github.io pull request #52
Opened 2023-12-26 11:03 UTC by dahhara

## 概要
DB 移行 PJ の主に8月~9月末の部分の記事を書いた。

## 備考
- DB 移行当日の夜は発散しすぎるので一旦書くのをやめた。
- 書くべきことが多すぎて、詳細の話は書くのを諦めた。
  - 特に社内説明会したとかそういう系の調整

2023-12-26 11:04 UTC, dahhara commented on public/content/db-migration-project-management/meeting-note.png
どこまで出していいのかな、という気持ちはある(具体の何かはわからんように塗りつぶして入る)

2023-12-26 11:29 UTC, thimi0412 requested changes

2023-12-26 11:29 UTC, thimi0412 commented on content/db-migration-project-management.md
> +7月の終わり頃、オフィスについた途端にデータエンジニアの [thimi041](https://twitter.com/thimi0412) さんに「dahhara さん、このままだとこれヤバいですよ」とアラートをもらったのが PJ 始動のきっかけです。
```suggestion
7月の終わり頃、オフィスについた途端にデータエンジニアの [thimi0412](https://twitter.com/thimi0412) さんに「dahhara さん、このままだとこれヤバいですよ」とアラートをもらったのが PJ 始動のきっかけです。
```

2023-12-26 11:29 UTC, thimi0412 commented on content/db-migration-project-management.md
> +
ここに作業してる写真入れてもいいのかなって思いました。

2023-12-26 11:29 UTC, thimi0412 commented on content/db-migration-project-management.md
> +とりわけ、技術負債としては特に DB へのコネクション数がボトルネックとなっており、その解消を図るべく2023年は期初から GCP の CloudSQL からよりハイスペックな AlloyDB への移行をメンバーへ委譲して進めていました。
AllroyDBのlinkがあってもいいと思いました

2023-12-26 11:29 UTC, thimi0412 commented on public/content/db-migration-project-management/meeting-note.png
https://github.com/wedinc/communication/issues/50
の事前準備、当日スケジュール、DB移行後も見せてもいいのかなって思いました

2023-12-27 04:01 UTC, ryuya-matsunawa commented on content/db-migration-project-management.md
> +2. 飛び石の作業時間によるパフォーマンスの低下する。
```suggestion
2. 飛び石の作業時間によりパフォーマンスが低下する。
```

2024-01-04 05:05 UTC, kazsKAZAMA commented on content/db-migration-project-management.md
> +とりわけ、技術負債としては特に DB へのコネクション数がボトルネックとなっており、その解消を図るべく2023年は期初から GCP の CloudSQL からよりハイスペックな AlloyDB への移行をメンバーへ委譲して進めていました。
> CloudSQL からよりハイスペックな AlloyDB
物理的なスペックはそんなに変わらないですね
表現として、ハイパフォーマンス　の方が適切かと思います

2024-01-04 05:54 UTC, thimi0412 approved these changes

2024-01-05 02:00 UTC, ryuya-matsunawa approved these changes

2024-01-09 06:42 UTC, dahhara commented
@kazsKAZAMA 
対応したので、お手すきで再レビューをお願いします！

2024-01-09 08:53 UTC, kazsKAZAMA approved these changes

2024-01-09 09:37 UTC, merged